# Generated by Django 4.0.3 on 2023-03-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleshistory',
            name='buyer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='saleshistory',
            name='seller',
            field=models.CharField(max_length=200),
        ),
    ]
