# Generated by Django 4.0.3 on 2023-03-08 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_alter_automobilevo_import_href_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technician',
            old_name='employee_id',
            new_name='employee_number',
        ),
    ]
