# Generated by Django 4.0.3 on 2023-03-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_rename_employee_id_technician_employee_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
